export enum ContractStatusEnum {
  AVAILABLE = 'DISPONIBLE',
  SELLED = 'VENDIDO',
  PAIDOFF = 'LIQUIDADO',
  APART = 'APARTADO',
  RELOCATE = 'REUBICAR',
  SRMIGUEL = 'SR.MIGUEL',
  TAKEN = 'INVADIDO',
  AFFECTED = 'AFECTADO',
  DISMISSED = 'BAJA',
}
